use("accounts");

db.getCollection("users").insertMany([
  {
    personID: 1,
    firstname: "Peter",
    lastname: "Parker",
    dob: new Date("1998-06-05"),
    age: 25,
    debt: 5000,
    balance: 10000,
    email: "dummy@mail.com",
    phone: 5555555555,
    address: {
      street: "123 main street",
      city: "LA",
      pincode: "46732",
    },
    hobbies: ["spider-manning", "photography", "spending time with MJ"],
    alive: true,
  },
  {
    personID: 2,
    firstname: "Bruce",
    lastname: "Wayne",
    dob: new Date("1983-02-19"),
    age: 40,
    debt: 100000,
    balance: 100000000,
    email: "brucewayne@wayneenterprises.com",
    phone: 1234567890,
    address: {
      street: "1007 Mountain Drive",
      city: "Gotham City",
      pincode: "45678",
    },
    hobbies: ["being Batman", "philanthropy", "collecting cars"],
    alive: true,
  },
  {
    personID: 3,
    firstname: "Clark",
    lastname: "Kent",
    dob: new Date("1988-07-18"),
    age: 35,
    debt: 0,
    balance: 10000000000,
    email: "clarkkent@dailyplanet.com",
    phone: 9876543210,
    address: {
      street: "3400 North Clark Street",
      city: "Metropolis",
      pincode: "12345",
    },
    hobbies: [
      "being Superman",
      "reporting for the Daily Planet",
      "saving the world",
    ],
    alive: true,
  },
  {
    personID: 4,
    firstname: "Diana",
    lastname: "Prince",
    dob: new Date("4000-01-01"),
    age: 5000,
    debt: 0,
    balance: 1000000000000,
    email: "wonderwoman@themyscira.com",
    phone: 5555555555,
    address: {
      street: "Themyscira Island",
      city: "Themyscira",
      pincode: "12345",
    },
    hobbies: [
      "being Wonder Woman",
      "fighting crime",
      "protecting the innocent",
    ],
    alive: true,
  },
  {
    personID: 5,
    firstname: "Steve",
    lastname: "Rogers",
    dob: new Date("1922-07-04"),
    age: 100,
    debt: 0,
    balance: 10000000000000,
    email: "captainamerica@avengershq.com",
    phone: 9876543210,
    address: {
      street: "135 West 50th Street",
      city: "New York City",
      pincode: "10020",
    },
    hobbies: [
      "being Captain America",
      "leading the Avengers",
      "protecting the United States",
    ],
    alive: true,
  },

  {
    personID: 6,
    firstname: "Tony",
    lastname: "Stark",
    dob: new Date("1978-05-29"),
    age: 45,
    debt: 100000000,
    balance: 100000000000,
    email: "ironman@starkindustries.com",
    phone: 5555555555,
    address: {
      street: "125 West 72nd Street",
      city: "New York City",
      pincode: "10023",
    },
    hobbies: [
      "being Iron Man",
      "building gadgets and armor",
      "running Stark Industries",
    ],
    alive: true,
  },
  {
    personID: 7,
    firstname: "Natasha",
    lastname: "Romanoff",
    dob: new Date("1988-01-25"),
    age: 35,
    debt: 0,
    balance: 100000000,
    email: "blackwidow@avengershq.com",
    phone: 9876543210,
    address: {
      street: "135 West 50th Street",
      city: "New York City",
      pincode: "10020",
    },
    hobbies: [
      "being Black Widow",
      "spying, fighting, and assassinating bad guys",
    ],
    alive: true,
  },
  {
    personID: 8,
    firstname: "Clint",
    lastname: "Barton",
    dob: new Date("1983-01-07"),
    age: 40,
    debt: 0,
    balance: 100000000,
    email: "hawkeye@avengershq.com",
    phone: 5555555555,
    address: {
      street: "135 West 50th Street",
      city: "New York City",
      pincode: "10020",
    },
    hobbies: ["being Hawkeye", "being a dad, and shooting arrows"],
    alive: true,
  },
  {
    personID: 9,
    firstname: "Wanda",
    lastname: "Maximoff",
    dob: new Date("1993-02-16"),
    age: 30,
    debt: 0,
    balance: 100000000,
    email: "scarletwitch@avengershq.com",
    phone: 9876543210,
    address: {
      street: "135 West 50th Street",
      city: "New York City",
      pincode: "10020",
    },
    hobbies: [
      "being the Scarlet Witch",
      "using her powers to protect the people she loves",
    ],
    alive: true,
  },
  {
    personID: 10,
    firstname: "Vision",
    lastname: "Synthezoid",
    dob: new Date("2020-08-07"),
    age: 3,
    debt: 0,
    balance: 100000000,
    email: "vision@avengershq.com",
    phone: 5555555555,
    address: {
      street: "135 West 50th Street",
      city: "New York City",
      pincode: "10020",
    },
    hobbies: ["being the Vision", "using his powers to help people"],
    alive: true,
  },

  {
    personID: 11,
    firstname: "John",
    lastname: "Doe",
    dob: new Date("1998-03-12"),
    age: 25,
    debt: 10000,
    balance: 10000,
    email: "johndoe@gmail.com",
    phone: 9876543210,
    address: {
      street: "123 Main Street",
      city: "Anytown",
      pincode: "12345",
    },
    hobbies: ["reading", "writing", "coding"],
    alive: true,
  },
  {
    personID: 12,
    firstname: "Jane",
    lastname: "Smith",
    dob: new Date("1978-05-08"),
    age: 45,
    debt: 0,
    balance: 1000000,
    email: "janesmith@yahoo.com",
    phone: 5555555555,
    address: {
      street: "456 Elm Street",
      city: "Everytown",
      pincode: "56789",
    },
    hobbies: ["sports", "travel", "photography"],
    alive: true,
  },
  {
    personID: 13,
    firstname: "Mary",
    lastname: "Jones",
    dob: new Date("1993-01-25"),
    age: 30,
    debt: 0,
    balance: 500000,
    email: "maryjones@hotmail.com",
    phone: 9876543210,
    address: {
      street: "789 Oak Street",
      city: "Sometown",
      pincode: "90123",
    },
    hobbies: ["cooking", "gardening", "hiking"],
    alive: true,
  },
  {
    personID: 14,
    firstname: "David",
    lastname: "Williams",
    dob: new Date("1963-07-14"),
    age: 58,
    debt: 0,
    balance: 2000000,
    email: "davidwilliams@aol.com",
    phone: 1234567890,
    address: {
      street: "1011 Pine Street",
      city: "Nowheresville",
      pincode: "00000",
    },
    hobbies: ["music", "art", "movies"],
    alive: true,
  },
  {
    personID: 15,
    firstname: "Susan",
    lastname: "Miller",
    dob: new Date("1968-09-22"),
    age: 53,
    debt: 0,
    balance: 1000000,
    email: "susanmiller@comcast.net",
    phone: 5555555555,
    address: {
      street: "1112 Maple Street",
      city: "Anywhere",
      pincode: "12345",
    },
    hobbies: ["volunteering", "reading", "spending time with family"],
    alive: true,
  },
  {
    personID: 21,
    firstname: "Harry",
    lastname: "Bhai",
    dob: new Date("1995-05-20"),
    age: 29,
    debt: 34000,
    balance: 33000,
    email: "hbrry@test.com",
    phone: 747474747747,
    address: {
      street: "344 street subway",
      city: "Heidi",
      pincode: "35353",
    },
    alive: true,
  },
]);
